fisch fisch fisch
If aliens were to invade earth, it would be for mspaint.
now i dont get heart attacks by rush, 10/10
mspaint is swag at its finest
i have no idea why its called mspaint but its cool
Ms paint is honestly something else, truly the peak of Roblox doors scripting.
zib zib zib zib zib zib zib. Zib zib zib!✅👍
I couldn’t figure out how to paint, but the script is good
---> content <---
Better well stolen than poorly invented.
erm what the sigma
downloading... "ZIP bomb.zip" - progress: 99%
If you're reading this, mspaint is loaded WWWW!!!!!11!1!
sigma sigma on the wall whos the brainrotted of htem all
How unfortunate, i now have your IP: 127.0.0.1 :content:
"miaw miaw miaw miaw" - upio
[1] If you're reading this, you need to drink water NOW!!
[2] If you're reading this, do a flip
[3] If you're reading this, then skibidi
BLZ wrote the following message: CAT GIRLS ARE REAL, YEEEAAHHH!!! UHUUULL
me a noob so i needed this 9/11
